import path from "node:path";
import { LogManager, type Logger } from "@bluecadet/launchpad-utils";
import autoBind from "auto-bind";
import type { SubEmitterSocket } from "axon";
import { Tail } from "tail";
import { LogModes, type ResolvedAppConfig } from "../monitor-config.js";

class LogRelay {
	protected _appOptions: ResolvedAppConfig;

	protected _logOptions: ResolvedAppConfig["logging"];

	protected _logger: Logger;

	constructor(appOptions: ResolvedAppConfig, logger: Logger) {
		logger.debug(`Saving output logs to ${appOptions.pm2.output}`);
		logger.debug(`Saving error logs to ${appOptions.pm2.error}`);

		// Writing to these fields for backwards compatiblity
		// @see https://pm2.keymetrics.io/docs/usage/application-declaration/#log-files
		appOptions.pm2.out_file = appOptions.pm2.output;
		appOptions.pm2.error_file = appOptions.pm2.error;

		if (appOptions.pm2.output !== "/dev/null" || appOptions.pm2.error !== "/dev/null") {
			logger.warn("Launchpad is unable to rotate log files generated by pm2");
			logger.warn("Set log mode to 'bus' and unset pm2 output/error properties to hide this warning.");
		}

		this._appOptions = appOptions;
		this._logOptions = appOptions.logging;
		this._logger = logger;
	}

	handleEvent(_eventType: string, _eventData: unknown) {
		// implement this fn in all child classes
		throw new Error("not implemented");
	}
}

class FileLogRelay extends LogRelay {
	#outTail: Tail | null = null;
	#errTail: Tail | null = null;

	constructor(appOptions: ResolvedAppConfig, logger: Logger) {
		const appName = appOptions.pm2.name;

		if (appOptions.logging.logToLaunchpadDir) {
			// Move app logs from default pm2 dir to launchpad dir
			const outPath = LogManager.getInstance().getFilePath(`${appName}-stdout`);
			const errPath = LogManager.getInstance().getFilePath(`${appName}-stderr`);
			appOptions.pm2.output ??= path.resolve(outPath);
			appOptions.pm2.error ??= path.resolve(errPath);
		} else {
			appOptions.pm2.output = undefined;
			appOptions.pm2.error = undefined;
		}

		super(appOptions, logger);
	}

	// biome-ignore lint/suspicious/noExplicitAny: TODO: fix this
	override handleEvent(eventType: string, eventData: any) {
		switch (eventType) {
			case "process:event":
				if (eventData.event === "online") this.#handleOnline();
				else if (eventData.event === "exit") this.#handleOffline();
				break;
			default:
				break;
		}
	}

	#handleOnline() {
		const tailOptions = {
			useWatchFile: true,
			fsWatchOptions: { interval: 100 },
		};
		const outFilepath = this._appOptions.pm2.output;
		const errFilepath = this._appOptions.pm2.error;

		if (this.#outTail) {
			this.#outTail.unwatch();
			this.#outTail = null;
		}
		if (this.#errTail) {
			this.#errTail.unwatch();
			this.#errTail = null;
		}

		if (!outFilepath) {
			this._logger.warn(`App process for ${this._appOptions.pm2.name} is missing the 'output' property.`);
		}
		if (!errFilepath) {
			this._logger.warn(`App process for ${this._appOptions.pm2.name} is missing the 'error' property.`);
		}

		if (outFilepath && this._logOptions.showStdout) {
			this._logger.debug(`Tailing stdout from ${outFilepath}`);
			this.#outTail = new Tail(outFilepath, tailOptions);
			this.#outTail.on("line", (data) => this.#handleTailOutput(data));
			this.#outTail.on("error", (data) => this.#handleTailError(data, true));
			this.#outTail.watch();
		}

		if (errFilepath && this._logOptions.showStderr) {
			this._logger.debug(`Tailing stderr from ${errFilepath}`);
			this.#errTail = new Tail(errFilepath, tailOptions);
			this.#errTail.on("line", (data) => this.#handleTailError(data));
			this.#errTail.on("error", (data) => this.#handleTailError(data, true));
			this.#errTail.watch();
		}
	}

	#handleOffline() {
		if (this.#outTail) {
			this.#outTail.unwatch();
			this.#outTail = null;
		}
		if (this.#errTail) {
			this.#errTail.unwatch();
			this.#errTail = null;
		}
	}

	#handleTailOutput(data: string) {
		if (this._logOptions.showStdout) {
			this._logger.info(data);
		}
	}

	#handleTailError(data: string, isTailError = false) {
		if (isTailError || this._logOptions.showStderr) {
			this._logger.error(data);
		}
	}
}

class BusLogRelay extends LogRelay {
	constructor(appOptions: ResolvedAppConfig, logger: Logger) {
		// default log outputs to '/dev/null' if not defined
		appOptions.pm2.output ??= "/dev/null";
		appOptions.pm2.error ??= "/dev/null";

		super(appOptions, logger);
	}

	override handleEvent(eventType: string, eventData: { data: string }) {
		switch (eventType) {
			case "log:out":
				this.#handleBusLogOut(eventData);
				break;
			case "log:err":
				this.#handleBusLogErr(eventData);
				break;
			default:
				break;
		}
	}

	#splitLines(buffer: string) {
		const parts = buffer.split(/[\r]{0,1}\n/);
		parts.pop(); // last item will always be an empty string because every line ends with a carriage return
		return parts;
	}

	#handleBusLogOut(event: { data: string }) {
		if (this._logOptions.showStdout) {
			for (const line of this.#splitLines(event.data.toString())) {
				this._logger.info(line);
			}
		}
	}

	#handleBusLogErr(event: { data: string }) {
		if (this._logOptions.showStderr) {
			for (const line of this.#splitLines(event.data.toString())) {
				this._logger.error(line);
			}
		}
	}
}

export default class AppLogRouter {
	#logger: Logger;
	#logRelays = new Map<string, LogRelay>();

	constructor(logger: Logger) {
		autoBind(this);
		this.#logger = logger;
	}

	initAppOptions(appOptions: ResolvedAppConfig) {
		const pm2Options = appOptions.pm2;
		const logOptions = appOptions.logging;
		const appName = pm2Options.name ?? pm2Options.script ?? "[unnamed app]";

		const appLogger = LogManager.getLogger(appName, this.#logger);

		if (logOptions.mode === LogModes.TailLogFile) {
			const fileRelay = new FileLogRelay(appOptions, appLogger);
			this.#logRelays.set(appName, fileRelay);
		} else {
			const busRelay = new BusLogRelay(appOptions, appLogger);
			this.#logRelays.set(appName, busRelay);
		}
	}

	connectToBus(pm2Bus: SubEmitterSocket) {
		pm2Bus.on("*", this.#handleEvent.bind(this));
	}

	disconnectFromBus(pm2Bus: SubEmitterSocket) {
		pm2Bus.off("*");
	}

	#handleEvent(eventType: string, eventData: { process: { name: string } }) {
		if (!eventData?.process?.name) return;
		this.#logRelays.get(eventData.process.name)?.handleEvent(eventType, eventData);
	}
}
